services:
  llama-server:
    build:
      context: .
    image: frt/llama
    container_name: llama
    shm_size: '128g'
    mem_limit: '110g'
    volumes:
      - ./data:/mnt
    ports:
      - 18080:18080
    gpus: all
